name: CI

on: push

env:
  TURBO_CACHE_DIR: ".turbo"
  NODE_VER: 14

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VER }}
          cache: "npm"
      - name: cache turborepo
        uses: actions/cache@v3
        with:
          path: ${{ env.TURBO_CACHE_DIR }}
          key: turbo-${{ github.job }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}
            turbo
      - run: npm i
      - run: npm i -g npm@9
      - run: npm run lint --cache-dir=$TURBO_CACHE_DIR

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VER }}
          cache: "npm"
      - name: cache turborepo
        uses: actions/cache@v3
        with:
          path: ${{ env.TURBO_CACHE_DIR }}
          key: turbo-${{ github.job }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}
            turbo
      - run: npm i
      - run: npm i -g npm@9
      - run: npm run build --cache-dir=$TURBO_CACHE_DIR

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VER }}
          cache: "npm"
      - name: cache turborepo
        uses: actions/cache@v3
        with:
          path: ${{ env.TURBO_CACHE_DIR }}
          key: turbo-${{ github.job }}-${{ github.sha }}
          restore-keys: |
            turbo-${{ github.job }}
            turbo
      - run: npm i
      - run: npm i -g npm@9
      - run: npm exec firebase emulators:exec 'npm test --cache-dir=$TURBO_CACHE_DIR'
